version: '3'

services:
  derailed:
    build: front-derails
    hostname: derailed
    container_name: derailed-service
    restart: on-failure
    ports:
      - "8080:80"

volumes:
  derailed-data:
