version: '2'
services:
  derailed-backend:
    build: .
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:4::2
  derailed-frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - derailed-backend
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:4::1
networks:
  checkernet:
    external: true
